services:
  # --- DEVELOPMENT SERVICES ---
  db:
    image: postgis/postgis:15-3.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=nearby
      - POSTGRES_PASSWORD=nearby
      - POSTGRES_DB=nearbynearby
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nearby -d nearbynearby"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://nearby:nearby@db/nearbynearby
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend

  # --- TESTING SERVICES ---
  test-db:
    image: postgis/postgis:15-3.4
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpassword
      - POSTGRES_DB=testdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d testdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    # No ports or volumes needed, it's only for internal use

  test:
    build: ./backend
    command: ["pytest"]
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://testuser:testpassword@test-db/testdb
      - TESTING=True
    depends_on:
      test-db:
        condition: service_healthy

volumes:
  postgres_data:
