"""Python loader for the POI field registry.

The single source of truth is ``shared/poi_fields.json`` (generated by
``scripts/gen_poi_registry.py`` and validated by ``shared/poi_fields.schema.json``).
This module loads it once, caches the parsed list, and exposes a small set of
helpers used by the backend serializer (phase B3) and the contract tests.

Dependency-light: stdlib ``json`` only.
"""

from __future__ import annotations

import json
import os
from functools import lru_cache
from typing import Any, Dict, List, Optional

# Resolve the registry path relative to THIS file so it works regardless of the
# current working directory or how the package is imported.
#   shared/constants/poi_registry.py  ->  shared/poi_fields.json
_REGISTRY_PATH = os.path.normpath(
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "poi_fields.json")
)


@lru_cache(maxsize=1)
def load_registry() -> List[Dict[str, Any]]:
    """Read and cache the parsed registry (a list of field-entry dicts).

    The result is cached for the lifetime of the process. The returned list is
    the shared cached object — callers MUST treat it as read-only.
    """
    with open(_REGISTRY_PATH, "r", encoding="utf-8") as fh:
        data = json.load(fh)
    if not isinstance(data, list):
        raise ValueError(
            f"poi_fields.json must be a JSON array, got {type(data).__name__}"
        )
    return data


def all_entries() -> List[Dict[str, Any]]:
    """Return every registry entry (including admin/partner + deprecated)."""
    return load_registry()


@lru_cache(maxsize=1)
def _by_key() -> Dict[str, Dict[str, Any]]:
    return {entry["key"]: entry for entry in load_registry()}


def field_by_key(key: str) -> Optional[Dict[str, Any]]:
    """Return the single entry whose ``key`` matches, or ``None``."""
    return _by_key().get(key)


def public_fields_for(poi_type: str) -> List[Dict[str, Any]]:
    """Return live, public entries that apply to ``poi_type``.

    An entry is included when:
      * ``audience == "public"``
      * ``poi_type`` is in ``applies_to``
      * ``deprecated`` is falsy

    Results are returned in registry ``order`` for stable, group-aware output.
    """
    entries = [
        entry
        for entry in load_registry()
        if entry.get("audience") == "public"
        and poi_type in entry.get("applies_to", [])
        and not entry.get("deprecated", False)
    ]
    return sorted(entries, key=lambda e: e.get("order", 0))
