"""Add binary storage fields to images table

Revision ID: 02830f53f66c
Revises: ab1234567890
Create Date: 2025-09-20 23:29:55.070533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02830f53f66c'
down_revision = 'ab1234567890'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('image_data', sa.LargeBinary(), nullable=True))
    op.add_column('images', sa.Column('image_size_variant', sa.String(length=20), nullable=True))
    op.add_column('images', sa.Column('parent_image_id', sa.UUID(), nullable=True))
    op.add_column('images', sa.Column('is_optimized', sa.Boolean(), nullable=True))
    op.add_column('images', sa.Column('storage_provider', sa.String(length=50), nullable=True))
    op.add_column('images', sa.Column('storage_url', sa.String(length=500), nullable=True))
    op.add_column('images', sa.Column('storage_key', sa.String(length=255), nullable=True))
    op.add_column('images', sa.Column('quality', sa.Integer(), nullable=True))
    op.add_column('images', sa.Column('format_optimized', sa.String(length=10), nullable=True))
    op.add_column('images', sa.Column('compression_ratio', sa.Integer(), nullable=True))
    op.drop_index(op.f('idx_images_poi_id'), table_name='images')
    op.drop_index(op.f('idx_images_poi_type'), table_name='images')
    op.drop_index(op.f('idx_images_type'), table_name='images')
    op.create_foreign_key(None, 'images', 'images', ['parent_image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.create_index(op.f('idx_images_type'), 'images', ['image_type'], unique=False)
    op.create_index(op.f('idx_images_poi_type'), 'images', ['poi_id', 'image_type'], unique=False)
    op.create_index(op.f('idx_images_poi_id'), 'images', ['poi_id'], unique=False)
    op.drop_column('images', 'compression_ratio')
    op.drop_column('images', 'format_optimized')
    op.drop_column('images', 'quality')
    op.drop_column('images', 'storage_key')
    op.drop_column('images', 'storage_url')
    op.drop_column('images', 'storage_provider')
    op.drop_column('images', 'is_optimized')
    op.drop_column('images', 'parent_image_id')
    op.drop_column('images', 'image_size_variant')
    op.drop_column('images', 'image_data')
    # ### end Alembic commands ###