"""Add publication_status field to POI model

Revision ID: 09ea2ce8061d
Revises: 31c82dc5953a
Create Date: 2025-09-17 00:26:04.847580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09ea2ce8061d'
down_revision = '31c82dc5953a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points_of_interest', sa.Column('publication_status', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('points_of_interest', 'publication_status')
    # ### end Alembic commands ###