"""create attributes table

Revision ID: 30c757d721f7
Revises: 706598f33ffd
Create Date: 2025-07-11 04:48:46.577805

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '30c757d721f7'
down_revision = '706598f33ffd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attributes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('applicable_to', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['attributes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('parks',
    sa.Column('poi_id', sa.UUID(), nullable=False),
    sa.Column('drone_usage_policy', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['poi_id'], ['points_of_interest.id'], ),
    sa.PrimaryKeyConstraint('poi_id')
    )
    op.create_table('poi_relationships',
    sa.Column('source_poi_id', sa.UUID(), nullable=False),
    sa.Column('target_poi_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['source_poi_id'], ['points_of_interest.id'], ),
    sa.ForeignKeyConstraint(['target_poi_id'], ['points_of_interest.id'], ),
    sa.PrimaryKeyConstraint('source_poi_id', 'target_poi_id', 'relationship_type')
    )
    op.create_table('trails',
    sa.Column('poi_id', sa.UUID(), nullable=False),
    sa.Column('length_text', sa.String(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('route_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['poi_id'], ['points_of_interest.id'], ),
    sa.PrimaryKeyConstraint('poi_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trails')
    op.drop_table('poi_relationships')
    op.drop_table('parks')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('attributes')
    # ### end Alembic commands ###