"""Add main_category_id to POI

Revision ID: 31c82dc5953a
Revises: a5098e000a95
Create Date: 2025-09-15 11:43:43.070596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31c82dc5953a'
down_revision = 'a5098e000a95'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points_of_interest', sa.Column('main_category_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'points_of_interest', 'categories', ['main_category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'points_of_interest', type_='foreignkey')
    op.drop_column('points_of_interest', 'main_category_id')
    # ### end Alembic commands ###