"""Add fields for Stories 9-11: Park Trail Event enhancements

Revision ID: 4ee80a69f047
Revises: cfcfa84c570b
Create Date: 2025-09-17 03:19:31.023355

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4ee80a69f047'
down_revision = 'cfcfa84c570b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('venue_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('events', sa.Column('event_entry_notes', sa.Text(), nullable=True))
    op.add_column('events', sa.Column('event_entry_photo', sa.String(), nullable=True))
    op.add_column('points_of_interest', sa.Column('payphone_locations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('points_of_interest', sa.Column('park_entry_notes', sa.Text(), nullable=True))
    op.add_column('points_of_interest', sa.Column('park_entry_photo', sa.String(), nullable=True))
    op.add_column('points_of_interest', sa.Column('parking_lot_photo', sa.String(), nullable=True))
    op.add_column('points_of_interest', sa.Column('facilities_options', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('trails', sa.Column('trailhead_latitude', sa.Numeric(precision=10, scale=7), nullable=True))
    op.add_column('trails', sa.Column('trailhead_longitude', sa.Numeric(precision=10, scale=7), nullable=True))
    op.add_column('trails', sa.Column('trailhead_photo', sa.String(), nullable=True))
    op.add_column('trails', sa.Column('trail_exit_latitude', sa.Numeric(precision=10, scale=7), nullable=True))
    op.add_column('trails', sa.Column('trail_exit_longitude', sa.Numeric(precision=10, scale=7), nullable=True))
    op.add_column('trails', sa.Column('trail_exit_photo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trails', 'trail_exit_photo')
    op.drop_column('trails', 'trail_exit_longitude')
    op.drop_column('trails', 'trail_exit_latitude')
    op.drop_column('trails', 'trailhead_photo')
    op.drop_column('trails', 'trailhead_longitude')
    op.drop_column('trails', 'trailhead_latitude')
    op.drop_column('points_of_interest', 'facilities_options')
    op.drop_column('points_of_interest', 'parking_lot_photo')
    op.drop_column('points_of_interest', 'park_entry_photo')
    op.drop_column('points_of_interest', 'park_entry_notes')
    op.drop_column('points_of_interest', 'payphone_locations')
    op.drop_column('events', 'event_entry_photo')
    op.drop_column('events', 'event_entry_notes')
    op.drop_column('events', 'venue_settings')
    # ### end Alembic commands ###