"""Add listing types, cost fields, teaser, ideal_for, and event repeat fields

Revision ID: 604c6b25cd30
Revises: 30c757d721f7
Create Date: 2025-08-18 23:15:09.938687

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '604c6b25cd30'
down_revision = '30c757d721f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'listing_tier')
    op.add_column('events', sa.Column('is_repeating', sa.Boolean(), nullable=True))
    op.add_column('events', sa.Column('repeat_pattern', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('events', 'cost_text')
    op.add_column('points_of_interest', sa.Column('teaser_paragraph', sa.String(length=120), nullable=True))
    op.add_column('points_of_interest', sa.Column('dont_display_location', sa.Boolean(), nullable=True))
    op.add_column('points_of_interest', sa.Column('listing_type', sa.String(length=50), nullable=True))
    op.add_column('points_of_interest', sa.Column('cost', sa.String(length=100), nullable=True))
    op.add_column('points_of_interest', sa.Column('pricing_details', sa.Text(), nullable=True))
    op.add_column('points_of_interest', sa.Column('ticket_link', sa.String(), nullable=True))
    op.add_column('points_of_interest', sa.Column('ideal_for', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('points_of_interest', 'ideal_for')
    op.drop_column('points_of_interest', 'ticket_link')
    op.drop_column('points_of_interest', 'pricing_details')
    op.drop_column('points_of_interest', 'cost')
    op.drop_column('points_of_interest', 'listing_type')
    op.drop_column('points_of_interest', 'dont_display_location')
    op.drop_column('points_of_interest', 'teaser_paragraph')
    op.add_column('events', sa.Column('cost_text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('events', 'repeat_pattern')
    op.drop_column('events', 'is_repeating')
    op.add_column('businesses', sa.Column('listing_tier', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###