"""Implement poi_categories table with is_main boolean per Story 3 technical notes

Revision ID: e6318f242755
Revises: 4ee80a69f047
Create Date: 2025-09-17 04:10:19.790970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6318f242755'
down_revision = '4ee80a69f047'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poi_categories',
    sa.Column('poi_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['poi_id'], ['points_of_interest.id'], ),
    sa.PrimaryKeyConstraint('poi_id', 'category_id')
    )
    op.drop_constraint(op.f('points_of_interest_main_category_id_fkey'), 'points_of_interest', type_='foreignkey')
    op.drop_column('points_of_interest', 'main_category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points_of_interest', sa.Column('main_category_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('points_of_interest_main_category_id_fkey'), 'points_of_interest', 'categories', ['main_category_id'], ['id'])
    op.drop_table('poi_categories')
    # ### end Alembic commands ###