"""Add business details, menu booking, and community fields

Revision ID: f24b3f3ceff3
Revises: 6f67dca3dc46
Create Date: 2025-08-18 23:53:52.001447

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f24b3f3ceff3'
down_revision = '6f67dca3dc46'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points_of_interest', sa.Column('rental_photos', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('points_of_interest', sa.Column('price_range_per_person', sa.String(), nullable=True))
    op.add_column('points_of_interest', sa.Column('pricing', sa.String(), nullable=True))
    op.add_column('points_of_interest', sa.Column('discounts', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('points_of_interest', sa.Column('gift_cards', sa.String(), nullable=True))
    op.add_column('points_of_interest', sa.Column('youth_amenities', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('points_of_interest', sa.Column('business_amenities', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('points_of_interest', sa.Column('entertainment_options', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('points_of_interest', sa.Column('menu_photos', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('points_of_interest', sa.Column('menu_link', sa.String(), nullable=True))
    op.add_column('points_of_interest', sa.Column('delivery_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('points_of_interest', sa.Column('reservation_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('points_of_interest', sa.Column('appointment_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('points_of_interest', sa.Column('online_ordering_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('points_of_interest', sa.Column('service_locations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('points_of_interest', sa.Column('locally_found_at', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('points_of_interest', sa.Column('article_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('points_of_interest', sa.Column('community_impact', sa.Text(), nullable=True))
    op.add_column('points_of_interest', sa.Column('organization_memberships', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('points_of_interest', 'organization_memberships')
    op.drop_column('points_of_interest', 'community_impact')
    op.drop_column('points_of_interest', 'article_links')
    op.drop_column('points_of_interest', 'locally_found_at')
    op.drop_column('points_of_interest', 'service_locations')
    op.drop_column('points_of_interest', 'online_ordering_links')
    op.drop_column('points_of_interest', 'appointment_links')
    op.drop_column('points_of_interest', 'reservation_links')
    op.drop_column('points_of_interest', 'delivery_links')
    op.drop_column('points_of_interest', 'menu_link')
    op.drop_column('points_of_interest', 'menu_photos')
    op.drop_column('points_of_interest', 'entertainment_options')
    op.drop_column('points_of_interest', 'business_amenities')
    op.drop_column('points_of_interest', 'youth_amenities')
    op.drop_column('points_of_interest', 'gift_cards')
    op.drop_column('points_of_interest', 'discounts')
    op.drop_column('points_of_interest', 'pricing')
    op.drop_column('points_of_interest', 'price_range_per_person')
    op.drop_column('points_of_interest', 'rental_photos')
    # ### end Alembic commands ###