/**
 * Frontend loader for the POI field registry.
 *
 * The single source of truth is the repo-root `shared/poi_fields.json`
 * (generated by `scripts/gen_poi_registry.py`, validated by
 * `shared/poi_fields.schema.json`). The frontend Docker build stage only has
 * access to `nearby-app/app/`, so the registry is mirrored to
 * `src/data/poi_fields.json` (kept byte-identical to the shared copy) and
 * imported here. Vite natively supports JSON imports.
 *
 * The registry-valid test (`tests/test_registry_valid.py`) and the contract
 * test guard the SHARED copy; a separate drift check keeps the mirror in sync.
 */

import registry from '../data/poi_fields.json';

/** Every registry entry (including admin/partner + deprecated). */
export function allEntries() {
  return registry;
}

/** Return the single entry whose `key` matches, or `undefined`. */
export function fieldByKey(key) {
  return registry.find((entry) => entry.key === key);
}

/**
 * Live, public entries that apply to `type`, sorted by registry `order`.
 *
 * An entry is included when:
 *   - audience === 'public'
 *   - applies_to includes `type`
 *   - not deprecated
 */
export function publicFieldsFor(type) {
  return registry
    .filter(
      (entry) =>
        entry.audience === 'public' &&
        Array.isArray(entry.applies_to) &&
        entry.applies_to.includes(type) &&
        !entry.deprecated
    )
    .sort((a, b) => (a.order ?? 0) - (b.order ?? 0));
}

/**
 * Ordered groups of auto-render public fields for `type`.
 *
 * Only fields with `render === 'auto'` are returned (bespoke/hidden fields are
 * rendered by dedicated components, not the generic auto-renderer). Groups are
 * ordered by the minimum field `order` within each group, and fields inside a
 * group keep registry order.
 *
 * Returns: [{ group: string, fields: Entry[] }, ...]
 */
export function groupsFor(type) {
  const autoFields = publicFieldsFor(type).filter(
    (entry) => entry.render === 'auto'
  );

  const groupOrder = [];
  const grouped = new Map();
  for (const entry of autoFields) {
    const name = entry.group;
    if (!grouped.has(name)) {
      grouped.set(name, []);
      groupOrder.push(name);
    }
    grouped.get(name).push(entry);
  }

  return groupOrder.map((name) => ({ group: name, fields: grouped.get(name) }));
}
