"""Add Story 7 and 8 business form fields

Revision ID: 5813795ee621
Revises: 09ea2ce8061d
Create Date: 2025-09-17 02:59:44.902743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5813795ee621'
down_revision = '09ea2ce8061d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###