"""Add contact fields, history, featured image, and holiday hours

Revision ID: 6f67dca3dc46
Revises: 2ca2f15a25ca
Create Date: 2025-08-18 23:43:22.047330

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6f67dca3dc46'
down_revision = '2ca2f15a25ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points_of_interest', sa.Column('history_paragraph', sa.Text(), nullable=True))
    op.add_column('points_of_interest', sa.Column('featured_image', sa.String(), nullable=True))
    op.add_column('points_of_interest', sa.Column('main_contact_name', sa.String(), nullable=True))
    op.add_column('points_of_interest', sa.Column('main_contact_email', sa.String(), nullable=True))
    op.add_column('points_of_interest', sa.Column('main_contact_phone', sa.String(), nullable=True))
    op.add_column('points_of_interest', sa.Column('offsite_emergency_contact', sa.Text(), nullable=True))
    op.add_column('points_of_interest', sa.Column('emergency_protocols', sa.Text(), nullable=True))
    op.add_column('points_of_interest', sa.Column('ideal_for_key', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('points_of_interest', sa.Column('holiday_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('points_of_interest', 'holiday_hours')
    op.drop_column('points_of_interest', 'ideal_for_key')
    op.drop_column('points_of_interest', 'emergency_protocols')
    op.drop_column('points_of_interest', 'offsite_emergency_contact')
    op.drop_column('points_of_interest', 'main_contact_phone')
    op.drop_column('points_of_interest', 'main_contact_email')
    op.drop_column('points_of_interest', 'main_contact_name')
    op.drop_column('points_of_interest', 'featured_image')
    op.drop_column('points_of_interest', 'history_paragraph')
    # ### end Alembic commands ###