"""Add shopping center and park system fields

Revision ID: a116e7e2d582
Revises: 02830f53f66c
Create Date: 2025-09-21 06:42:59.074357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a116e7e2d582'
down_revision = '02830f53f66c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points_of_interest', sa.Column('shopping_center', sa.String(), nullable=True))
    op.add_column('points_of_interest', sa.Column('park_system', sa.String(), nullable=True))
    op.add_column('points_of_interest', sa.Column('park_manager', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('points_of_interest', 'park_manager')
    op.drop_column('points_of_interest', 'park_system')
    op.drop_column('points_of_interest', 'shopping_center')
    # ### end Alembic commands ###