"""Add is_main_category field to categories

Revision ID: a5098e000a95
Revises: ec25961c5647
Create Date: 2025-09-15 11:42:30.137888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5098e000a95'
down_revision = 'ec25961c5647'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('is_main_category', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'is_main_category')
    # ### end Alembic commands ###