"""Add new data collection fields

Revision ID: c7d8e9f0a1b2
Revises: a1b2c3d4e5f6
Create Date: 2025-06-15 03:45:10.123456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c7d8e9f0a1b2'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns to 'businesses' table
    op.add_column('businesses', sa.Column('contact_name', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('contact_email', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('contact_phone', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('is_service_business', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # Add columns to 'locations' table
    op.add_column('locations', sa.Column('use_coordinates_for_map', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('locations', sa.Column('entry_notes', sa.Text(), nullable=True))
    op.add_column('locations', sa.Column('entrance_photo_url', sa.String(), nullable=True))

    # Add columns to 'points_of_interest' table
    op.add_column('points_of_interest', sa.Column('summary', sa.String(length=200), nullable=True))
    op.add_column('points_of_interest', sa.Column('status_message', sa.String(length=80), nullable=True))
    op.add_column('points_of_interest', sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('points_of_interest', sa.Column('featured_image_url', sa.String(), nullable=True))
    op.add_column('points_of_interest', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('points_of_interest', sa.Column('parent_poi_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key('fk_poi_parent_id', 'points_of_interest', 'points_of_interest', ['parent_poi_id'], ['id'])
    
    # Update status default value to reflect the new primary status
    op.alter_column('points_of_interest', 'status', server_default='Fully Open')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert status default
    op.alter_column('points_of_interest', 'status', server_default='active')

    # Drop columns from 'points_of_interest'
    op.drop_constraint('fk_poi_parent_id', 'points_of_interest', type_='foreignkey')
    op.drop_column('points_of_interest', 'parent_poi_id')
    op.drop_column('points_of_interest', 'updated_at')
    op.drop_column('points_of_interest', 'featured_image_url')
    op.drop_column('points_of_interest', 'is_verified')
    op.drop_column('points_of_interest', 'status_message')
    op.drop_column('points_of_interest', 'summary')
    
    # Drop columns from 'locations'
    op.drop_column('locations', 'entrance_photo_url')
    op.drop_column('locations', 'entry_notes')
    op.drop_column('locations', 'use_coordinates_for_map')
    
    # Drop columns from 'businesses'
    op.drop_column('businesses', 'is_service_business')
    op.drop_column('businesses', 'contact_phone')
    op.drop_column('businesses', 'contact_email')
    op.drop_column('businesses', 'contact_name')
    # ### end Alembic commands ###