"""Add new business form fields for stories 7 and 8

Revision ID: cfcfa84c570b
Revises: 5813795ee621
Create Date: 2025-09-17 03:02:07.849104

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cfcfa84c570b'
down_revision = '5813795ee621'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points_of_interest', sa.Column('address_county', sa.String(), nullable=True))
    op.add_column('points_of_interest', sa.Column('front_door_latitude', sa.Numeric(precision=10, scale=7), nullable=True))
    op.add_column('points_of_interest', sa.Column('front_door_longitude', sa.Numeric(precision=10, scale=7), nullable=True))
    op.add_column('points_of_interest', sa.Column('gallery_photos', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('points_of_interest', sa.Column('business_entry_notes', sa.Text(), nullable=True))
    op.add_column('points_of_interest', sa.Column('business_entry_photo', sa.String(), nullable=True))
    op.add_column('points_of_interest', sa.Column('appointment_booking_url', sa.String(), nullable=True))
    op.add_column('points_of_interest', sa.Column('hours_but_appointment_required', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('points_of_interest', 'hours_but_appointment_required')
    op.drop_column('points_of_interest', 'appointment_booking_url')
    op.drop_column('points_of_interest', 'business_entry_photo')
    op.drop_column('points_of_interest', 'business_entry_notes')
    op.drop_column('points_of_interest', 'gallery_photos')
    op.drop_column('points_of_interest', 'front_door_longitude')
    op.drop_column('points_of_interest', 'front_door_latitude')
    op.drop_column('points_of_interest', 'address_county')
    # ### end Alembic commands ###