import UpdateLayout from './UpdateLayout';

function RuralSmallTownAmerica() {
  return (
    <UpdateLayout
      title="Rural and Small Town America Deserves Better. Here Is What We Have Been Doing About It."
      dateLabel="June 5, 2026"
      image="/media/featured-image-rural-and-small-town-america-deserves-better-here-is-what-we-have-been-doing-about-it-01.webp"
      excerpt={"On America’s 250th birthday, we are bringing community, independence, and resilience to the places that have always embodied those values and have too often been left to do it alone."}
    >
      <p>The last time we posted here, we were talking about what 2025 was going to look like for Nearby Nearby. What we did not know then was just how much ground we were about to cover, how many rooms we were about to walk into, and how many things we were about to learn, or the amazing mentors that would step up and guide our path.</p>
      <p>This is the catch-up post. All of it, or as much as fits.</p>
      <h2 className="title_style_3">2025: The Year the Doors Opened</h2>
      <p>If 2025 had a theme, it was this: the right people started paying attention.</p>
      <p>We were selected for programs that do not take everyone. We were invited to pitch on stages we had to earn our way onto. We were asked to be in rooms where the conversations about rural America, rural technology, and rural resilience were actually happening. And we showed up to every single one.</p>
      <p>We started the year in three programs at once. The <a href="https://nasdaqcenter.org/milestone-circles/" target="_blank" rel="noopener noreferrer">Nasdaq Milestone Circles Program</a> , a 12-week cohort that pushed us to get serious about our business fundamentals. The <a href="https://business.campbell.edu/about/entrepreneurship/camel-accelerator/" target="_blank" rel="noopener noreferrer">Campbell University Camel Accelerator</a> , a 10-week program that sharpened how we tell our story and think about growth. And we were already deep into the <a href="https://grepbeat.com/2024/11/15/ceds-eighth-gro-incubator-wraps-up-12-week-program-with-demo-day/" target="_blank" rel="noopener noreferrer">CED GRO Accelerator</a> .</p>
      <p>That set the tone for everything that followed.</p>
      <p>We pitched everywhere. <a href="https://grepbeat.com/2025/03/28/venture-connect-2025-highlights-takeaways-and-photos/" target="_blank" rel="noopener noreferrer">Venture Connect hosted by CED</a> . <a href="https://www.thelaunchplace.org/news/details/id/254/the-launch-place-holds-its-10th-ideafest" target="_blank" rel="noopener noreferrer">Launch Place IdeaFest</a> . <a href="https://www.techstars.com" target="_blank" rel="noopener noreferrer">Techstars Pizza and Pitches,</a> where we won our group. The <a href="https://www.nctech.org/resources/blog/2025/startup-showcase-feature.html" target="_blank" rel="noopener noreferrer">NC State of Technology Exponential</a> . <a href="https://grepbeat.com/2025/05/13/eight-startups-selected-to-pitch-for-5k-prize-at-grep-a-palooza-2025/" target="_blank" rel="noopener noreferrer">Grep-a-Palooza.</a> <a href="https://www.lilalearning.org" target="_blank" rel="noopener noreferrer">LILA Deal or No Deal.</a> <a href="https://www.ncbiotech.org/events/converge-south-2025" target="_blank" rel="noopener noreferrer">Convergence South.</a> <a href="https://grepbeat.com/2025/10/14/riot-holds-packed-demo-night-at-raleigh-convention-center/" target="_blank" rel="noopener noreferrer">RIoT Demo Night</a> at the Raleigh Convention Center. <a href="https://riot.org/innovation-takes-center-stage-in-pittsboro-riots-rap-xxi-founder-showcase-pitch-night/" target="_blank" rel="noopener noreferrer">RIoT Pitch Event</a> . Founder, Rhonda Jean, was a panelist for the <a href="https://entrepreneurship.ncsu.edu/event/startup-horror-stories-2025/" target="_blank" rel="noopener noreferrer">Startup Horror Stories Panel at NC State Innovation and Entrepreneurship</a> . We attended <a href="https://www.raleighdurhamstartupweek.com" target="_blank" rel="noopener noreferrer">Raleigh Durham Startup Week</a> . The <a href="https://www.uplifttourism.com/rural-tourism-summit" target="_blank" rel="noopener noreferrer">UPLIFT Rural Tourism Summit</a> . <a href="https://outdooreconomy.org" target="_blank" rel="noopener noreferrer">The Outdoor Economy Conference</a> , where we had a booth.</p>
      <p>We also joined the <a href="https://pittsboronc.gov/CivicAlerts.aspx?AID=195&ARC=337" target="_blank" rel="noopener noreferrer">RIoT 21st Inaugural Accelerator right here in Pittsboro</a> , which felt like coming home in a lot of ways.</p>
      <p>We worked with two separate teams through the <a href="https://courses.learnmore.duke.edu/search/publicCourseSearchDetails.do?method=load&courseId=10605876" target="_blank" rel="noopener noreferrer">Duke Design Thinking and Innovation Program.</a> We worked with Daniel through the <a href="https://sbtdc.org/services/technology-commercialization/internship" target="_blank" rel="noopener noreferrer">SBTDC Summer Internship Program</a> . We attended the Chatham Ag Summit hosted by the West Chatham Chamber. We showed up to as many Chatham Chamber, West Chatham Chamber, CED, Chatham County Economic Development, GrepBeat, Wake Up Wednesday in Pittsboro, and Wake Up with the Chamber in Siler City events as we possibly could.</p>
      <h2 className="title_style_3">Western North Carolina and Why It Changed Everything</h2>
      <p>After Hurricane Helene, we did not sit still. We kept making drives to western North Carolina. We showed up at the <a href="https://averyltrg.org" target="_blank" rel="noopener noreferrer">Avery County Long Term Recovery Meetings</a> at Grandfather Mountain. We stayed connected to the communities that were still in the middle of recovering long after the news cameras left. We were at <a href="https://www.mountainbizworks.org" target="_blank" rel="noopener noreferrer">Mountain Rise at Highland Brewing in Asheville</a> , presented by Mountain BizWorks, there to support the businesses of western North Carolina that were still standing, still fighting, still open after Helene.</p>
      <p>Through the work we had done with the <a href="https://wcen-wnc.org" target="_blank" rel="noopener noreferrer">Western Carolina Emergency Network</a> in the immediate aftermath, helping move over 300,000 gallons of donated fuel across western North Carolina to survivors and communities in need, Founder, Rhonda Jean, received the <a href="https://www.prlog.org/13080492-western-carolina-emergency-network-accepts-2025-readycommunities-partnershipccroa-national-service-award-for-collaboration-to-augment-local-response.html" target="_blank" rel="noopener noreferrer">ReadyConnect Award from Washington, D.C</a> .</p>
      <p>Rhonda Jean is grateful for that recognition. But what it really did was make clearer than ever what Nearby Nearby is actually for. Not just finding what is nearby on a normal Tuesday. Finding what is open, where help is, and how communities can coordinate their own needs when everything else breaks down.</p>
      <p>That clarity shaped everything that came next.</p>
      <h2 className="title_style_3">Meeting Manav and Learning to Speak a New Language</h2>
      <p>One of the most important things that happened in 2025 happened right after Techstars Pizza and Pitches, when Manav from Tesslate came up and asked what our biggest hurdle was to getting launched. The answer was straightforward: we needed $1.2 million to build the technology.</p>
      <p>He offered to build it instead.</p>
      <p>What followed was one of the most humbling, frustrating, and ultimately rewarding learning curves of this entire journey.</p>
      <p>Here is the honest version. I am a visual thinker and an overexplainer. Manav and his team needed the problem in a simple, clean statement. I kept giving them paintings when they needed blueprints. Learning to translate every idea in my head into something a developer could actually build has taken months of dedicated work, more YouTube than I care to admit, and a lot of patience on both sides.</p>
      <p>But it’s clicking. And what we are building together, with Barry bringing the visuals to life, is looking really good.</p>
      <h2 className="title_style_3">December 9, 2025: The Decision</h2>
      <p>After months of disaster relief work, accelerators, pitches, and hard conversations about what Nearby Nearby was really trying to do, Founder Rhonda Jean made a decision.</p>
      <p>On December 9, 2025, Founder Rhonda Jean committed to starting <a href="https://nearbynearbynetwork.org" target="_blank" rel="noopener noreferrer">Nearby Nearby Network</a> as an independent nonprofit.</p>
      <p>The platform could handle local discovery and economic visibility. But the resilience work, the grassroots hub infrastructure, the communication systems that work when cell service fails, that needed its own structure, its own funding model, and its own mission.</p>
      <p>And there was a deeper reason. Founder Rhonda Jean, wanted the disaster resilience tools we are building to always be free for rural and small town communities to access. No subscription. No paywall. No version of the future where someone inherits this work and decides to change that. Structuring it as a nonprofit with its own governance was the only way to protect that commitment permanently. Money should never be a barrier for a small rural community trying to coordinate its own needs during a devastating time for them. That principle needed to be built into the legal structure itself, not just the mission statement.</p>
      <p>That decision set the entire tone for 2026.</p>
      <h2 className="title_style_3">2026: Getting Serious</h2>
      <p>If 2025 was the year the doors opened, 2026 has been the year we walked through them with a plan.</p>
      <p>We started with a New Year’s Day dessert and open house at <a href="https://thequiltmakercafe.org" target="_blank" rel="noopener noreferrer">Quiltmaker Cafe in Pittsboro</a> , a small moment that felt like a reset. Then we got to work.</p>
      <p>We traveled to Greenville to meet <a href="https://business.ecu.edu/faculty/yeagere18/" target="_blank" rel="noopener noreferrer">Emily at East Carolina University</a> . We sat down with <a href="https://www.mercycorps.org" target="_blank" rel="noopener noreferrer">Maria Gomez at Mercy Corps</a> , <a href="https://provost.ncsu.edu/global-one-health-academy/people/thomas-j-white/" target="_blank" rel="noopener noreferrer">Tom White at NC State</a> , <a href="https://www.commerce.nc.gov/about-us/commerce-leadership/assistant-secretary-rural-economic-development-reginald-speight" target="_blank" rel="noopener noreferrer">Reginald Speight with the Rural Secretary of State’s office</a> , <a href="https://ced.sog.unc.edu/2016/02/02/u-s-eda-resources-help-communities-build-the-local-ecosystem-for-sustainable-economic-development/" target="_blank" rel="noopener noreferrer">Hillary Sherman at the EDA</a> , <a href="https://www.ncleg.gov/Members/Biography/s/416" target="_blank" rel="noopener noreferrer">Senator Ted Alexander,</a> Alan with the <a href="https://frcnc.gov" target="_blank" rel="noopener noreferrer">Foothills Regional Commission</a> , the team at <a href="https://ncrma.org" target="_blank" rel="noopener noreferrer">NCRMA</a> , and more people than we can name in one post. Every conversation sharpened what we were building and why.</p>
      <p>We attended the <a href="https://www.chathamchambernc.org" target="_blank" rel="noopener noreferrer">Chatham County Industry Appreciation Breakfast.</a> We started showing up to <a href="https://www.inclusivedisasterrecovery.org" target="_blank" rel="noopener noreferrer">NC Inclusive Disaster Recovery Network meetings</a> and learning from the people doing this work every day. We attended <a href="https://www.ncruralcenter.org/rural-summit/" target="_blank" rel="noopener noreferrer">Rural Summit</a> 2026. We pitched at <a href="https://grepbeat.com/2026/03/27/ceds-venture-connect-2026-two-packed-days-at-dpac/" target="_blank" rel="noopener noreferrer">Venture Connect 2026</a> . We sat down with Randy Voller for a conversation on <a href="https://chapelboro.com/wchl/features/on-the-porch/rhonda-jean-technology-trajectory#:~:text=Nearby%20Nearby%20shows%20results%20based,better%20access%20to%20local%20information." target="_blank" rel="noopener noreferrer">On the Porch</a> at 97.9 The Hill WCHL.</p>
      <p>On the legal side, we worked with <a href="https://law.unc.edu" target="_blank" rel="noopener noreferrer">UNC Law students</a> , sat through more attorney meetings than we can count for both the for-profit and the nonprofit, worked with the <a href="https://law.campbell.edu/advocate/clinical-programs/innovate-capital-business-law-clinic/" target="_blank" rel="noopener noreferrer">Campbell University Hutchens Clinic</a> , filed a response on our first patent with our attorney, and got our Nearby Nearby trademark secured.</p>
      <p>We researched and prepared a second entirely separate patent, reviewing so many patents art and getting close to filing.</p>
      <p>We were accepted into the <a href="https://nasalifelines.org/lifelines-gallery/connecting-rural-communities-to-earth-observation-for-pre-disaster-planning-in-north-carolina/" target="_blank" rel="noopener noreferrer">NASA Lifelines</a> program based on what we are building with the nonprofit and completed a case study with them.</p>
      <p>We did all the paperwork, all the compliance steps, and everything required to legally operate as a nonprofit in North Carolina. We hosted our first board meeting for Nearby Nearby Network. We worked with Barry on branding and design. We kept pushing the platform build forward with Manav as the custom database started to take real shape.</p>
      <p>This is also a big part of why we have been quiet on social media. Operating a for-profit and a nonprofit together carries real responsibility. I wanted every step we took, every post we shared, every partnership we mentioned, to be correct, compliant, and clearly within the lines. I never want either organization to come close to crossing a line. Getting that right took time. It was worth it.</p>
      <p>And we started working on an EDA application for disaster resilience funding.</p>
      <h2 className="title_style_3">What 2026 Is Actually About</h2>
      <p>America turns 250 years old this July 4. Two hundred and fifty years of communities building something from the ground up, neighbors showing up for each other, and small towns holding the fabric of this country together across 97% of its land.</p>
      <p>Those communities deserve better tools. They deserve to be visible, connected, and ready.</p>
      <p>Everything we are building, both Nearby Nearby the platform and <a href="https://nearbynearbynetwork.org" target="_blank" rel="noopener noreferrer">Nearby Nearby Network</a> the nonprofit, comes back to three things.</p>
      <p><strong>Community.</strong> Helping rural and small town America find what is around them, connect with local businesses, parks, trails, and events, and feel less invisible in a world that was not built with them in mind.</p>
      <p><strong>Independence.</strong> Giving communities tools that work for them, not platforms built around ad budgets and urban density. Not waiting for outside systems to arrive and tell them what they need. Building the kind of local infrastructure that lets communities coordinate their own needs and define their own recovery.</p>
      <p><strong>Resilience.</strong> Economic resilience that comes from being findable and visible every day. And physical resilience that comes from having the foundation already in place before the next disaster hits.</p>
      <p>On America’s 250th birthday, we are bringing community, independence, and resilience to the places that have always embodied those values and have too often been left to do it alone.</p>
      <p>Nearby Nearby is in Pittsboro, North Carolina first, expanding through Chatham County and then county by county across rural and small town America. Nearby Nearby Network is live, the listening tour is coming, and the work is real.</p>
      <p>We have been quiet. Now we are ready to show you what we have been building.</p>
      <p>More soon.</p>
    </UpdateLayout>
  );
}

export default RuralSmallTownAmerica;
